'use client'
import { type Metadata } from 'next'
import { type NextPage } from 'next'
import Head from 'next/head'
import { useSession } from 'next-auth/react'

export const metadata: Metadata = {
  title: 'Trang chủ',
  description: 'Trang chủ',
}

const Home: NextPage = () => {
  const session = useSession()
  return (
    <>
      <Head>
        <title>Khám Phá</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>alo</main>
    </>
  )
}

export default Home
