'use client'
import { type NextPage } from 'next'
import Head from 'next/head'
import { signIn, useSession, signOut } from 'next-auth/react'

const Home: NextPage = () => {
  const session = useSession()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>alo</main>
    </>
  )
}

export default Home
